name: adnald
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python
  - numpy
  - scipy
  - geos
  - proj4
  - pip
  - numba
  - msprime
  - cartopy
  - pip:
    - tskit
    - tszip
    - pandas
    - matplotlib
    - tqdm
    - patsy
    - statsmodels
    - geopy
